# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'require_all'
gem 'rspec'
gem 'pry-byebug'
gem 'rake'
gem 'sqlite3'

