# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'activerecord', '< 5.0'
gem 'sinatra-activerecord'
gem 'rake'
gem 'shotgun'
gem 'sqlite3'
gem 'pry-byebug'
gem 'require_all'
