# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'require_all'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pry'
gem 'sqlite3'
gem 'rake'
gem 'annotate'# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'require_all'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pry'
gem 'sqlite3'
gem 'rake'